################### FUZZYLLI PARAMETERS #########################
general:
    output_file: ./data/single_cylinder/single_cylinder.h5
    cache: ./data/cache
    load_if_cached: True
    save_cdm: True
    save_fdm: True
    save_wdm: False
    seed: 42

cosmology:
    # FDM mass [1e-22 eV]
    m22: 2.0
    # Fit redshift
    z: 4.0

background_density:
    # Velocity Anisotropy parameter [0,1)
    beta: [0.0]
    # Radial velocity dispersion in [km/s]
    sigma: [6.8]
    # Physical size of scale radius in [Mpc/h]
    r0: [3.7e-3]

phasespace_distribution:
    # Number of gradient descent steps
    epochs: [6000]
    # minimum fit radius in [cMpc/h]
    R_min: [1.e-4]

eigenstate_library:
    # Number of spatial points at which eigenstates are computed
    N: [8192]

domain:
    # Box size [cMpc/h]
    L: 0.167
    # Number of grid points per dimension
    N: 512

filament_ensemble:
    # length [cMpc/h]
    length: [0.167]
    # total mass of cylinder [Msun/h]
    mass: [5.e9]
    # vector in domain specifying the origin of the cylinder in units of L
    origin: [[0.5,0.5,0.5]]
    # unit vector specifying orintation of cylinder
    direction: [[1.,0.,0.]]
    # direction of x-axis in plane orthogonal to filament spine
    orientation: [[0.,1.,0.]]
